; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .


[env:stm32f103rct6_full]
platform = ststm32
board = genericSTM32F103RC
framework = stm32cube
board_build.mcu = stm32f103rct6
board_build.f_cpu = 72000000L
monitor_speed = 115200
upload_protocol = stlink

; Full build target: all modules included.
build_src_filter =
  -<*>
  +<Src/main.c>
  +<Src/hw_setup.c>
  +<Src/hw_port.c>
  +<Src/hwconf/hal_gpio.c>
  +<Src/cmsis_rtos_compat.h>
  +<Src/conf_general_f103.c>
  +<Src/conf_custom.c>
  +<Src/events.c>
  +<Src/timeout.c>
  +<Src/driver/*.c>
  +<Src/driver/nrf/*.c>
  +<Src/util/*.c>
  +<Src/comm/*.c>
  +<Src/applications/*.c>
  +<Src/applications/app_custom*.c>
  +<Src/applications/app_finn_*.c>
  +<Src/applications/app_er_*.c>
  +<Src/encoder/*.c>
  +<Src/imu/*.c>
  +<Src/libcanard/*.c>
  +<Src/motor/*.c>
  +<Src/flash_helper_f103.c>
  +<Src/crc.c>
  -<Src/flash_helper.c>
  -<Src/hwconf/board.c>
  +<include/RTOS/croutine.c>
  +<include/RTOS/event_groups.c>
  +<include/RTOS/list.c>
  +<include/RTOS/queue.c>
  +<include/RTOS/stream_buffer.c>
  +<include/RTOS/tasks.c>
  +<include/RTOS/timers.c>
  +<include/RTOS/portable/GCC/ARM_CM3/port.c>
  +<include/RTOS/portable/MemMang/heap_4.c>
  +<include/RTOS/CMSIS_RTOS_V2/cmsis_os2.c>

build_flags =
  ${env:stm32f103rct6_minimal.build_flags}
  -DHOVERBOARD_MINIMAL=0
  -DHOVERBOARD_CORE=0
  -DCAN_ENABLE=1
